// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAslBFf7rlwPVGzCscIM50yOKFi9xpT5J4',
    appId: '1:894982375882:web:e3ef6cecb58f0d9a3ee733',
    messagingSenderId: '894982375882',
    projectId: 'surakshasanket-210df',
    authDomain: 'surakshasanket-210df.firebaseapp.com',
    storageBucket: 'surakshasanket-210df.appspot.com',
    measurementId: 'G-XQ478F93NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsW3dpKe6BMdMDznN2sG0WqBq2s_fJkIc',
    appId: '1:894982375882:android:769307fe06de1db33ee733',
    messagingSenderId: '894982375882',
    projectId: 'surakshasanket-210df',
    storageBucket: 'surakshasanket-210df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkcHGx-BOTtLcA0lf2XA2Q3rPDqnLwgPg',
    appId: '1:894982375882:ios:183517f2a50a48283ee733',
    messagingSenderId: '894982375882',
    projectId: 'surakshasanket-210df',
    storageBucket: 'surakshasanket-210df.appspot.com',
    iosBundleId: 'com.help.co.help',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkcHGx-BOTtLcA0lf2XA2Q3rPDqnLwgPg',
    appId: '1:894982375882:ios:fe588e03848576663ee733',
    messagingSenderId: '894982375882',
    projectId: 'surakshasanket-210df',
    storageBucket: 'surakshasanket-210df.appspot.com',
    iosBundleId: 'com.help.co.help.RunnerTests',
  );
}
